# Default values for simple-webapp.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
nameOverride: ""
fullnameOverride: ""

resources:
  request:
    cpu: 100m
    memory: 100Mi

frontend:
  replicaCount: 3
  image:
    repository: us-docker.pkg.dev/google-samples/containers/gke/gb-frontend
    tag: v5
    pullPolicy: IfNotPresent
  service:
    type: NodePort
    port: 80
    nodePort: 31000
  env:
    GET_HOSTS_FROM: "dns"

redis:
  leader:
    replicaCount: 1
    image:
      repository: docker.io/redis
      tag: "6.0.5"
      pullPolicy: IfNotPresent
  follower:
    replicaCount: 2
    image:
      repository: us-docker.pkg.dev/google-samples/containers/gke/gb-redis-follower
      tag: v2
      pullPolicy: IfNotPresent
