apiVersion: v1
kind: Service
metadata:
  name: redis-follower
  labels:
    {{- include "simple-webapp.labels" . | nindent 4 }}
    app: redis
    role: follower
    tier: backend
spec:
  ports:
    - port: 6379
  selector:
    {{- include "simple-webapp.selectorLabels" . | nindent 4 }}
    app: redis
    role: follower
    tier: backend
