apiVersion: v1
kind: Service
metadata:
  name: redis-leader
  labels:
    {{- include "simple-webapp.labels" . | nindent 4 }}
    app: redis
    role: leader
    tier: backend
spec:
  ports:
    - port: 6379
      targetPort: 6379
  selector:
    {{- include "simple-webapp.selectorLabels" . | nindent 4 }}
    app: redis
    role: leader
    tier: backend
